version: '3'

services:
  server:
    build:
      context: .
    ports:
      - "3000:3000"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3001:3001"
    depends_on:
      - server
